security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2a$04$fRBpWHMBJqHnLs/Mkcl2Zexr4zp0Jmnh0BJLrsc.lErZQPzLIBrk6 # admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            form_login:
                  login_path: /login
                  check_path: /login_check
                  default_target_path: /admin

#        secured_area:
#            logout:
#                path:   /logout
#                target: /

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
